local M = {}

function M.get(palette)
  return {
    BufferLineFill = { bg = palette.bg_alt },
    BufferLineBackground = { fg = palette.comment, bg = palette.bg_alt },
    BufferLineBuffer = { fg = palette.fg_alt, bg = palette.bg_alt },
    BufferLineBufferVisible = { fg = palette.fg, bg = palette.bg },
    BufferLineBufferSelected = { fg = palette.fg, bg = palette.bg, bold = true },
    BufferLineDevIconLua = { fg = palette.orange },
    BufferLineDevIconCss = { fg = palette.blue },
    BufferLineDevIconHtml = { fg = palette.red },
    BufferLineDevIconJs = { fg = palette.yellow },
    BufferLineDevIconTs = { fg = palette.blue },
    BufferLineDevIconJson = { fg = palette.green },
    BufferLineDevIconMd = { fg = palette.fg },
    BufferLineDevIconNix = { fg = palette.blue },
    BufferLineDevIconToml = { fg = palette.purple },
    BufferLineDevIconYml = { fg = palette.red },
    BufferLineDevIconPy = { fg = palette.green },
    BufferLineTab = { fg = palette.fg_alt, bg = palette.bg_alt },
    BufferLineTabSelected = { fg = palette.fg, bg = palette.bg, sp = palette.green, bold = true },
    BufferLineTabClose = { fg = palette.comment, sp = palette.red },
    BufferLineSeparator = { fg = palette.border, bg = palette.bg_alt },
    BufferLineSeparatorVisible = { fg = palette.border, bg = palette.bg_alt },
    BufferLineSeparatorSelected = { fg = palette.border, bg = palette.bg },
    BufferLineCloseButton = { fg = palette.comment, bg = palette.bg_alt },
    BufferLineCloseButtonVisible = { fg = palette.fg_alt, bg = palette.bg_alt },
    BufferLineCloseButtonSelected = { fg = palette.red, bg = palette.bg },
    BufferLineModified = { fg = palette.warning, bg = palette.bg_alt },
    BufferLineModifiedVisible = { fg = palette.warning, bg = palette.bg_alt },
    BufferLineModifiedSelected = { fg = palette.warning, bg = palette.bg },
    BufferLineDuplicate = { fg = palette.comment, bg = palette.bg_alt },
    BufferLineDuplicateSelected = { fg = palette.comment, bg = palette.bg },
    BufferLinePick = { fg = palette.red, bg = palette.bg_alt, bold = true },
    BufferLinePickSelected = { fg = palette.red, bg = palette.bg, bold = true },
    BufferLinePickVisible = { fg = palette.red, bg = palette.bg_alt },
    BufferLineNumbers = { fg = palette.comment, bg = palette.bg_alt },
    BufferLineNumbersVisible = { fg = palette.fg_alt, bg = palette.bg_alt },
    BufferLineNumbersSelected = { fg = palette.fg, bg = palette.bg, bold = true },
    BufferLineHint = { fg = palette.hint, bg = palette.bg_alt },
    BufferLineHintVisible = { fg = palette.hint, bg = palette.bg_alt },
    BufferLineHintSelected = { fg = palette.hint, bg = palette.bg, bold = true },
    BufferLineError = { fg = palette.error, bg = palette.bg_alt },
    BufferLineErrorVisible = { fg = palette.error, bg = palette.bg_alt },
    BufferLineErrorSelected = { fg = palette.error, bg = palette.bg, bold = true },
    BufferLineWarning = { fg = palette.warning, bg = palette.bg_alt },
    BufferLineWarningVisible = { fg = palette.warning, bg = palette.bg_alt },
    BufferLineWarningSelected = { fg = palette.warning, bg = palette.bg, bold = true },
    BufferLineInfo = { fg = palette.info, bg = palette.bg_alt },
    BufferLineInfoVisible = { fg = palette.info, bg = palette.bg_alt },
    BufferLineInfoSelected = { fg = palette.info, bg = palette.bg, bold = true },
    BufferLineDiagnostics = { fg = palette.error, bg = palette.bg_alt },
    BufferLineDiagnosticsVisible = { fg = palette.error, bg = palette.bg_alt },
    BufferLineDiagnosticsSelected = { fg = palette.error, bg = palette.bg, bold = true },
    BufferLineTrunc = { fg = palette.comment, bg = palette.bg_alt },
    BufferLineTruncVisible = { fg = palette.comment, bg = palette.bg_alt },
    BufferLineTruncSelected = { fg = palette.comment, bg = palette.bg },
  }
end

return M
