local M = {}

function M.get(palette, config)
  return {
    Normal = { fg = palette.fg, bg = palette.bg },
    NormalFloat = { fg = palette.fg, bg = palette.bg_light },
    NormalNC = { fg = palette.fg },
    Cursor = { fg = palette.bg, bg = palette.cursor },
    CursorColumn = { bg = palette.cursorline },
    CursorLine = { bg = palette.cursorline },
    CursorLineNr = { fg = palette.yellow, bg = palette.cursorline },
    LineNr = { fg = palette.line_number },
    CursorLineSign = { fg = palette.fg_alt },
    CursorLineFold = { fg = palette.fg_alt },
    ColorColumn = { bg = palette.bg_alt },
    Conceal = { fg = palette.comment },
    Directory = { fg = palette.blue },
    DiffAdd = { fg = palette.green, bg = palette.bg_alt },
    DiffChange = { fg = palette.yellow, bg = palette.bg_alt },
    DiffDelete = { fg = palette.red, bg = palette.bg_alt },
    DiffText = { fg = palette.fg, bg = palette.bg_alt },
    EndOfBuffer = { fg = palette.bg },
    ErrorMsg = { fg = palette.error },
    FoldColumn = { fg = palette.fg_alt },
    Folded = { fg = palette.comment, bg = palette.bg_alt },
    SignColumn = { fg = palette.fg_alt },
    IncSearch = { fg = palette.bg, bg = palette.yellow },
    Substitute = { fg = palette.bg, bg = palette.yellow },
    Search = { fg = palette.bg, bg = palette.yellow, sp = palette.yellow },
    MatchParen = { fg = palette.yellow, bg = palette.selection, bold = true },
    ModeMsg = { fg = palette.fg },
    MsgArea = { fg = palette.fg },
    MoreMsg = { fg = palette.blue },
    NonText = { fg = palette.fg_gutter },
    Pmenu = { fg = palette.fg, bg = palette.bg_light },
    PmenuSel = { fg = palette.fg_alt, bg = palette.selection },
    PmenuSbar = { bg = palette.bg_alt },
    PmenuThumb = { bg = palette.comment },
    Question = { fg = palette.blue },
    QuickFixLine = { fg = palette.yellow, bg = palette.bg_alt, bold = true },
    SpecialKey = { fg = palette.fg_alt },
    SpellBad = { fg = palette.error, sp = palette.error, undercurl = true },
    SpellCap = { fg = palette.warning, sp = palette.warning, undercurl = true },
    SpellLocal = { fg = palette.info, sp = palette.info, undercurl = true },
    SpellRare = { fg = palette.hint, sp = palette.hint, undercurl = true },
    Title = { fg = palette.yellow, bold = true },
    Visual = { bg = palette.selection },
    VisualNOS = { fg = palette.fg, bg = palette.selection },
    WarningMsg = { fg = palette.warning },
    Whitespace = { fg = palette.fg_gutter },
    WildMenu = { fg = palette.bg, bg = palette.yellow },

    Comment = { fg = palette.comment, italic = config.styles.comments.italic },
    Todo = { fg = palette.warning, bg = palette.bg_alt, bold = true },
    Underlined = { fg = palette.cyan, sp = palette.cyan, underline = true },

    String = { fg = palette.green },
    Character = { fg = palette.green },
    Constant = { fg = palette.cyan },
    Number = { fg = palette.cyan },
    Boolean = { fg = palette.purple },
    Float = { fg = palette.cyan },

    Identifier = { fg = palette.fg },
    Function = { fg = palette.yellow },
    Keyword = { fg = palette.orange, italic = config.styles.keywords.italic },
    KeywordReturn = { fg = palette.red },
    Conditional = { fg = palette.red },
    Repeat = { fg = palette.red },
    Label = { fg = palette.orange },
    Operator = { fg = palette.pink },
    Exception = { fg = palette.red },
    Type = { fg = palette.orange },
    Typedef = { fg = palette.orange },
    StorageClass = { fg = palette.orange },
    Structure = { fg = palette.orange },

    PreProc = { fg = palette.orange },
    Include = { fg = palette.blue },
    Define = { fg = palette.pink },
    Macro = { fg = palette.yellow },
    PreCondit = { fg = palette.orange },

    Tag = { fg = palette.pink },
    Delimiter = { fg = palette.fg_alt },
    Special = { fg = palette.orange },
    SpecialChar = { fg = palette.orange },
    SpecialComment = { fg = palette.comment, bold = true },

    xmlTag = { fg = palette.pink },
    xmlTagName = { fg = palette.pink },
    xmlEndTag = { fg = palette.pink },
    xmlAttribute = { fg = palette.yellow },
    xmlString = { fg = palette.green },
    xmlAttrName = { fg = palette.yellow },

    htmlTag = { fg = palette.pink },
    htmlEndTag = { fg = palette.pink },
    htmlTagName = { fg = palette.pink },
    htmlAttribute = { fg = palette.yellow },
    htmlString = { fg = palette.green },

    cssSelector = { fg = palette.pink },
    cssSelectorOp = { fg = palette.pink },
    cssProperty = { fg = palette.green },
    cssValueNumber = { fg = palette.cyan },
    cssValueLength = { fg = palette.cyan },
    cssUnitDecorators = { fg = palette.cyan },
    cssClassName = { fg = palette.yellow },
    cssPseudoClassId = { fg = palette.yellow },
    cssPseudoClass = { fg = palette.yellow },

    tsxTag = { fg = palette.pink },
    tsxComponentName = { fg = palette.pink },
    tsxAttribute = { fg = palette.yellow },

    markdownHeadingDelimiter = { fg = palette.orange },
    markdownH1 = { fg = palette.orange, bold = true },
    markdownH2 = { fg = palette.orange, bold = true },
    markdownH3 = { fg = palette.orange, bold = true },
    markdownH4 = { fg = palette.orange, bold = true },
    markdownH5 = { fg = palette.orange, bold = true },
    markdownH6 = { fg = palette.orange, bold = true },
    markdownCode = { fg = palette.green },
    markdownCodeBlock = { fg = palette.green },
    markdownLink = { fg = palette.cyan, underline = true },
    markdownUrl = { fg = palette.cyan, underline = true },
    markdownListMarker = { fg = palette.orange },
    markdownBlockquote = { fg = palette.comment, italic = true },
    markdownRule = { fg = palette.comment },

    jsonString = { fg = palette.green },
    jsonNumber = { fg = palette.cyan },
    jsonBoolean = { fg = palette.purple },
    jsonNull = { fg = palette.purple },
    jsonKey = { fg = palette.yellow },
    jsonProperty = { fg = palette.yellow },

    yamlKey = { fg = palette.yellow },
    yamlNumber = { fg = palette.cyan },
    yamlString = { fg = palette.green },

    tomlKey = { fg = palette.yellow },
    tomlNumber = { fg = palette.cyan },
    tomlString = { fg = palette.green },

    diffAdded = { fg = palette.green },
    diffRemoved = { fg = palette.red },
    diffChanged = { fg = palette.yellow },
    diffOldFile = { fg = palette.red },
    diffNewFile = { fg = palette.green },
    diffFile = { fg = palette.blue },
    diffLine = { fg = palette.comment },

    DiagnosticError = { fg = palette.error },
    DiagnosticWarn = { fg = palette.warning },
    DiagnosticInfo = { fg = palette.info },
    DiagnosticHint = { fg = palette.hint },
    DiagnosticUnderlineError = { fg = palette.error, sp = palette.error, undercurl = true },
    DiagnosticUnderlineWarn = { fg = palette.warning, sp = palette.warning, undercurl = true },
    DiagnosticUnderlineInfo = { fg = palette.info, sp = palette.info, undercurl = true },
    DiagnosticUnderlineHint = { fg = palette.hint, sp = palette.hint, undercurl = true },

    NvimInternalError = { fg = palette.error, bg = palette.red },

    WinBar = { fg = palette.fg_alt, bg = palette.bg },
    WinBarNC = { fg = palette.comment, bg = palette.bg },

    NormalSB = { fg = palette.fg, bg = palette.sidebar.bg },
    StatusLine = { fg = palette.statusline.fg, bg = palette.statusline.bg },
    StatusLineNC = { fg = palette.fg_alt, bg = palette.bg_alt },

    TabLine = { fg = palette.tabline.fg, bg = palette.tabline.bg },
    TabLineFill = { fg = palette.fg, bg = palette.bg },
    TabLineSel = { fg = palette.tabline.fg_sel, bg = palette.tabline.bg_sel },

    VertSplit = { fg = palette.border, bg = palette.bg },
    WinSeparator = { fg = palette.border, bg = palette.bg },

    FloatBorder = { fg = palette.float_border, bg = palette.bg },
    FloatTitle = { fg = palette.fg, bg = palette.bg_light },

    CursorIM = { fg = palette.bg, bg = palette.cursor },

    Terminal = { fg = palette.fg, bg = palette.bg },

    ToolbarLine = { fg = palette.fg, bg = palette.bg_alt },
    ToolbarButton = { fg = palette.fg, bg = palette.bg_alt, bold = true },

    Error = { fg = palette.error, bg = palette.bg_alt },
    preProc = { fg = palette.orange },
    type = { fg = palette.orange },
    structure = { fg = palette.orange },
    special = { fg = palette.orange },
    debug = { fg = palette.red },
    marker = { fg = palette.orange },
  }
end

return M
