local M = {}

function M.get(palette, config)
  return {
    ["@comment"] = { fg = palette.comment, italic = true },
    ["@comment.lua"] = { fg = palette.comment, italic = true },
    ["@comment.todo"] = { fg = palette.warning, bold = true },
    ["@string"] = { fg = palette.green },
    ["@string.regexp"] = { fg = palette.cyan },
    ["@string.escape"] = { fg = palette.orange },
    ["@string.special"] = { fg = palette.green },
    ["@character"] = { fg = palette.green },
    ["@character.special"] = { fg = palette.orange },
    ["@boolean"] = { fg = palette.purple },
    ["@number"] = { fg = palette.cyan },
    ["@number.float"] = { fg = palette.cyan },
    ["@number.hex"] = { fg = palette.cyan },
    ["@number.octal"] = { fg = palette.cyan },
    ["@number.bin"] = { fg = palette.cyan },
    ["@constant"] = { fg = palette.cyan },
    ["@constant.builtin"] = { fg = palette.orange },
    ["@constant.macro"] = { fg = palette.orange },
    ["@define"] = { fg = palette.pink },
    ["@macro"] = { fg = palette.yellow },
    ["@preproc"] = { fg = palette.orange },
    ["@preproc.pragma"] = { fg = palette.pink },
    ["@type"] = { fg = palette.orange },
    ["@type.builtin"] = { fg = palette.orange },
    ["@type.qualifier"] = { fg = palette.orange },
    ["@type.definition"] = { fg = palette.orange },
    ["@storageclass"] = { fg = palette.orange },
    ["@storageclass.static"] = { fg = palette.orange },
    ["@storageclass.lifetime"] = { fg = palette.orange },
    ["@attribute"] = { fg = palette.yellow },
    ["@attribute.builtin"] = { fg = palette.yellow },
    ["@field"] = { fg = palette.yellow },
    ["@field.rust"] = { fg = palette.yellow },
    ["@property"] = { fg = palette.yellow },
    ["@variable"] = { fg = palette.fg },
    ["@variable.builtin"] = { fg = palette.orange },
    ["@variable.parameter"] = { fg = palette.magenta, italic = true },
    ["@variable.parameter.builtin"] = { fg = palette.magenta },
    ["@function"] = { fg = palette.yellow },
    ["@function.builtin"] = { fg = palette.yellow },
    ["@function.call"] = { fg = palette.yellow },
    ["@function.method"] = { fg = palette.yellow },
    ["@function.method.call"] = { fg = palette.yellow },
    ["@keyword"] = { fg = palette.orange, italic = config.styles.keywords.italic },
    ["@keyword.coroutine"] = { fg = palette.pink },
    ["@keyword.function"] = { fg = palette.orange },
    ["@keyword.operator"] = { fg = palette.pink },
    ["@keyword.return"] = { fg = palette.red },
    ["@keyword.control"] = { fg = palette.red },
    ["@keyword.control.conditional"] = { fg = palette.red },
    ["@keyword.control.repeat"] = { fg = palette.red },
    ["@keyword.control.import"] = { fg = palette.blue },
    ["@keyword.control.exception"] = { fg = palette.red },
    ["@label"] = { fg = palette.orange },
    ["@namespace"] = { fg = palette.yellow },
    ["@namespace.builtin"] = { fg = palette.yellow },
    ["@operator"] = { fg = palette.pink },
    ["@punctuation"] = { fg = palette.fg_alt },
    ["@punctuation.bracket"] = { fg = palette.fg_alt },
    ["@punctuation.delimiter"] = { fg = palette.fg_alt },
    ["@punctuation.special"] = { fg = palette.orange },
    ["@tag"] = { fg = palette.pink },
    ["@tag.attribute"] = { fg = palette.yellow },
    ["@tag.delimiter"] = { fg = palette.fg_alt },
    ["@tag.builtin"] = { fg = palette.pink },
    ["@text"] = { fg = palette.fg },
    ["@text.strong"] = { bold = true },
    ["@text.emphasis"] = { italic = true },
    ["@text.underline"] = { underline = true },
    ["@text.strike"] = { strikethrough = true },
    ["@text.title"] = { fg = palette.yellow, bold = true },
    ["@text.literal"] = { fg = palette.green },
    ["@text.link"] = { fg = palette.cyan, underline = true },
    ["@text.uri"] = { fg = palette.cyan, underline = true },
    ["@text.code"] = { fg = palette.green, bg = palette.bg_alt },
    ["@text.math"] = { fg = palette.orange },
    ["@text.environment"] = { fg = palette.orange },
    ["@text.environment.name"] = { fg = palette.pink },
    ["@text.reference"] = { fg = palette.cyan },
    ["@text.todo"] = { fg = palette.warning, bold = true },
    ["@text.note"] = { fg = palette.comment },
    ["@text.warning"] = { fg = palette.warning },
    ["@text.danger"] = { fg = palette.error },
    ["@text.diff.add"] = { fg = palette.green },
    ["@text.diff.delete"] = { fg = palette.red },
    ["@symbol"] = { fg = palette.orange },
    ["@debug"] = { fg = palette.red },
    ["@decorator"] = { fg = palette.yellow },
    ["@module"] = { fg = palette.yellow },
    ["@module.builtin"] = { fg = palette.yellow },
    ["@label"] = { fg = palette.orange },
  }
end

return M
